services:
  filters-ui:
    build:
      context: ./filters-ui
    ports:
      - "4200:80"
    depends_on:
      - filters-api

  filters-api:
    build:
      context: ./filters-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev